-- 14번(해결)
SELECT STUDENT_NAME AS "학생이름",
       NVL(PROFESSOR_NAME, '지도교수 미지정') AS "지도교수" -- NVL: NULL 값을 치환해주는 함수
FROM   TB_STUDENT S
LEFT JOIN TB_PROFESSOR ON (COACH_PROFESSOR_NO = PROFESSOR_NO)
LEFT JOIN TB_DEPARTMENT D ON(S.DEPARTMENT_NO = D.DEPARTMENT_NO)
WHERE  D.DEPARTMENT_NAME = '서반아어학과'
ORDER BY STUDENT_NO ;


-- 15번
SELECT  STUDENT_NO 학번,
        STUDENT_NAME 이름,
        DEPARTMENT_NAME 학과이름,
        TRUNC(AVG(POINT),2) 평점
FROM    TB_STUDENT
JOIN    TB_DEPARTMENT USING(DEPARTMENT_NO)
JOIN    TB_GRADE USING(STUDENT_NO)
WHERE   ABSENCE_YN = 'N'
HAVING  AVG(POINT) >= 4
GROUP BY    STUDENT_NO,
            STUDENT_NAME,
            DEPARTMENT_NAME;
            
-- 16번
SELECT  CLASS_NO,
        CLASS_NAME,
        TRUNC(AVG(POINT),2)
FROM    TB_CLASS
JOIN    TB_GRADE USING(CLASS_NO)
WHERE   DEPARTMENT_NO = (SELECT DEPARTMENT_NO
                         FROM   TB_DEPARTMENT
                         WHERE  DEPARTMENT_NAME = '환경조경학과')
        AND SUBSTR(CLASS_TYPE,1,2) = '전공'
GROUP BY  CLASS_NO,
          CLASS_NAME;

-- 17번
SELECT  STUDENT_NAME,
        STUDENT_ADDRESS
FROM    TB_STUDENT
WHERE   DEPARTMENT_NO = (SELECT DEPARTMENT_NO
                         FROM   TB_STUDENT
                         WHERE  STUDENT_NAME = '최경희');
                         
-- 18번(해결)
SELECT  STUDENT_NO,
        STUDENT_NAME
FROM (
	SELECT STUDENT_NAME,
	STUDENT_NO,
	AVG(POINT),
	RANK() OVER(ORDER BY AVG(POINT) DESC) AS RANK
			FROM   TB_DEPARTMENT
			JOIN   TB_CLASS USING (DEPARTMENT_NO)
			JOIN   TB_GRADE USING (CLASS_NO)
			JOIN   TB_STUDENT USING (STUDENT_NO)
			WHERE  DEPARTMENT_NAME = '국어국문학과'
			GROUP BY STUDENT_NAME, STUDENT_NO 
)
WHERE RANK = '1';

            
-- 19번(해결)
SELECT DEPARTMENT_NAME AS "계열 학과명",
			 ROUND(AVG(POINT), 1) AS "전공평점"
FROM   TB_DEPARTMENT 
JOIN   TB_CLASS C USING (DEPARTMENT_NO)
JOIN   TB_GRADE USING (CLASS_NO)
WHERE  CATEGORY IN(
                   SELECT CATEGORY
                   FROM TB_DEPARTMENT
                   WHERE DEPARTMENT_NAME = '환경조경학과'
                   )
GROUP BY DEPARTMENT_NAME
ORDER BY 1;
